# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c25553ced635a4d621bddd14f91dcc208c5115109a432a87e67e95d0efde3625aa5baeb3e7a1eeedb509475ed4eff516230822422f9cec4a199cd024b724ea80

test:
  secret_key_base: 93dd50c08e144ff949ac0bf8c995c9540458a0e5da4f003823fd4629e2158a2a3f9ae56383f2308ebcb7f9ca7dcc102a5267f2f9b4c5e0b6081cfbd196d456ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
